# Generated by Django 4.2.1 on 2023-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='another_image',
            field=models.ImageField(blank=True, null=True, upload_to='another_product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='another_image_thumbnail',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
